artifact_uri: /home/siryorch/Documents/aprendizaje/productrecognition/Testing/runs/mlflow/488246022360787059/3fc3ef8d0c0a45aaa234134cc0ecf633/artifacts
end_time: 1769406549725
entry_point_name: ''
experiment_id: '488246022360787059'
lifecycle_stage: active
run_id: 3fc3ef8d0c0a45aaa234134cc0ecf633
run_name: demo_yolo11n_coco128
run_uuid: 3fc3ef8d0c0a45aaa234134cc0ecf633
source_name: ''
source_type: 4
source_version: ''
start_time: 1769406418906
status: 4
tags: []
user_id: siryorch
