artifact_location: /home/siryorch/Documents/aprendizaje/productrecognition/Testing/runs/mlflow/488246022360787059
creation_time: 1769406246621
experiment_id: '488246022360787059'
last_update_time: 1769406246621
lifecycle_stage: active
name: product_recognition/models
