artifact_location: /home/siryorch/Documents/aprendizaje/productrecognition/Testing/runs/mlflow/0
creation_time: 1769406246615
experiment_id: '0'
last_update_time: 1769406246615
lifecycle_stage: active
name: Default
